# Generated by Django 4.1.7 on 2023-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_movies_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=400)),
                ('rating', models.IntegerField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(default='no-slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default='no-slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
