# Generated by Django 4.1.7 on 2023-05-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_movies_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='films.movies'),
            preserve_default=False,
        ),
    ]
