# Generated by Django 4.1.7 on 2023-05-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_comment_author_name_remove_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
